{
    "openapi": "3.0.1",
    "info": {
        "title": "Inventory Management",
        "description": "Maintaining up-to-date inventory for items on Walmart.com ensures a great customer experience as well as greater sales opportunities. The Inventory Management APIs allow management of current or recently changed inventory supply."
    },
    "servers": [
        {
            "url": "https:\/\/api-gateway.walmart.com",
            "description": "Production URL"
        }
    ],
    "paths": {
        "\/v3\/inventory": {
            "get": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Inventory",
                "description": "Gets the inventory for a given item.",
                "operationId": "getInventoryForAnItem",
                "parameters": [
                    {
                        "name": "sku",
                        "in": "query",
                        "description": "An arbitrary alphanumeric unique ID, specified by the DSV, which identifies each item. This will be used by the DSV in the XSD file to refer to each item. Special characters in the sku needing encoding are: ':', '\/', '?', '#', '[', ']', '@', '!', '$', '&', \"'\", '(', ')', '*', '+', ',', ';', '=', \u2018 \u2019, '{', '}' as well as '%' itself if it's a part of sku. Make sure to encode space with %20. Other characters don't need to be encoded.",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The Distribution Facility \u201cDistributor ID\u201d which uniquely identifies each facility and is autogenerated during DSV account creation. Every time you add\/update a facility in the Supplier Center, a new ID is generated",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_CONSUMER.CHANNEL.TYPE",
                        "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_QOS.CORRELATION_ID",
                        "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "b3261d2d-028a-4ef7-8602-633c23200af6",
                        "x-jane-skip-validation": true
                    },
                    {
                        "in": "header",
                        "name": "WM_SVC.NAME",
                        "description": "Walmart Service Name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Walmart Service Name",
                        "x-jane-skip-validation": true
                    },
                    {
                        "name": "WM_SEC.TIMESTAMP",
                        "in": "header",
                        "description": "The Epoch timestamp",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "1443748249449"
                    },
                    {
                        "name": "WM_SEC.AUTH_SIGNATURE",
                        "in": "header",
                        "description": "The vendor's digital signature, generated by running the JAR file or custom generation code",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "9fg3TPeRt0WSGbXNGGj4kSQ9L6PMBX.....9Zj5aDyg="
                    },
                    {
                        "name": "WM_CONSUMER.ID",
                        "in": "header",
                        "description": "A unique ID required to access the API",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Get the Consumer ID from Developer Center after logging in"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/xml": {
                                "schema": {
                                    "required": [
                                        "quantity",
                                        "sku"
                                    ],
                                    "type": "object",
                                    "properties": {
                                        "sku": {
                                            "type": "string",
                                            "description": "A DSV-provided Product ID. Response will have decoded value."
                                        },
                                        "quantity": {
                                            "required": [
                                                "amount",
                                                "unit"
                                            ],
                                            "type": "object",
                                            "properties": {
                                                "unit": {
                                                    "type": "string",
                                                    "description": "The unit of measurement. Example: 'EACH'",
                                                    "enum": [
                                                        "EACH"
                                                    ]
                                                },
                                                "amount": {
                                                    "type": "number",
                                                    "description": "The number available in the inventory"
                                                }
                                            },
                                            "description": "Information about the quantity in inventory"
                                        }
                                    },
                                    "xml": {
                                        "name": "Inventory"
                                    }
                                },
                                "example": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<inventory xmlns:ns2=\"http:\/\/walmart.com\/\">\n    <sku>1487132332472<\/sku>\n    <quantity>\n        <unit>EACH<\/unit>\n        <amount>23<\/amount>\n    <\/quantity>\n<\/inventory>\n"
                            },
                            "application\/json": {
                                "schema": {
                                    "required": [
                                        "quantity",
                                        "sku"
                                    ],
                                    "type": "object",
                                    "properties": {
                                        "sku": {
                                            "type": "string",
                                            "description": "A DSV-provided Product ID. Response will have decoded value."
                                        },
                                        "quantity": {
                                            "required": [
                                                "amount",
                                                "unit"
                                            ],
                                            "type": "object",
                                            "properties": {
                                                "unit": {
                                                    "type": "string",
                                                    "description": "The unit of measurement. Example: 'EACH'",
                                                    "enum": [
                                                        "EACH"
                                                    ]
                                                },
                                                "amount": {
                                                    "type": "number",
                                                    "description": "The number available in the inventory"
                                                }
                                            },
                                            "description": "Information about the quantity in inventory"
                                        }
                                    },
                                    "xml": {
                                        "name": "Inventory"
                                    }
                                },
                                "example": {
                                    "sku": "1487132332472",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 23
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Update inventory",
                "description": "Updates the inventory for a given item. Use an Availability Code to identify how inventory quantity is managed for an item.\n\nThe Availability Code can be:\n\nAC: Use for standard inventory updates. Assign this code to an item with normal inventory.\nAA: Use for an item with infinite inventory that never runs out. If you set the Availability Code to AA, you don't need to provide the quantity.\nPO: Use for a pre-order item.",
                "operationId": "updateInventoryForAnItem",
                "parameters": [
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The Distribution Facility \u201cDistributor ID\u201d which uniquely identifies each facility and is autogenerated during DSV account creation. Every time you add\/update a facility in the Supplier Center, a new ID is generated",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_CONSUMER.CHANNEL.TYPE",
                        "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_QOS.CORRELATION_ID",
                        "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "b3261d2d-028a-4ef7-8602-633c23200af6",
                        "x-jane-skip-validation": true
                    },
                    {
                        "in": "header",
                        "name": "WM_SVC.NAME",
                        "description": "Walmart Service Name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Walmart Service Name",
                        "x-jane-skip-validation": true
                    },
                    {
                        "name": "WM_SEC.TIMESTAMP",
                        "in": "header",
                        "description": "The Epoch timestamp",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "1443748249449"
                    },
                    {
                        "name": "WM_SEC.AUTH_SIGNATURE",
                        "in": "header",
                        "description": "The vendor's digital signature, generated by running the JAR file or custom generation code",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "9fg3TPeRt0WSGbXNGGj4kSQ9L6PMBX.....9Zj5aDyg="
                    },
                    {
                        "name": "WM_CONSUMER.ID",
                        "in": "header",
                        "description": "A unique ID required to access the API",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Get the Consumer ID from Developer Center after logging in"
                    }
                ],
                "requestBody": {
                    "description": "File fields",
                    "content": {
                        "application\/xml": {
                            "schema": {
                                "required": [
                                    "availabilityCode",
                                    "quantity",
                                    "sku"
                                ],
                                "type": "object",
                                "properties": {
                                    "sku": {
                                        "type": "string",
                                        "description": "A DSV-provided Product ID. Response will have decoded value."
                                    },
                                    "availabilityCode": {
                                        "type": "string",
                                        "description": "Identifies how to manage the inventory update. AC: The code used for standard inventory updates. Assign this code to an item with normal inventory. AA: An item with infinite inventory. If you set AA as the Availability Code, you don't need to provide inventory for the item.",
                                        "enum": [
                                            "AA",
                                            "AC",
                                            "PO"
                                        ]
                                    },
                                    "quantity": {
                                        "required": [
                                            "unit"
                                        ],
                                        "type": "object",
                                        "properties": {
                                            "unit": {
                                                "type": "string",
                                                "description": "The description of the quantity. Use 'Each' as shown in the provided sample.",
                                                "enum": [
                                                    "EACH"
                                                ]
                                            },
                                            "amount": {
                                                "type": "number",
                                                "description": "The number of the inventory quantity"
                                            },
                                            "availableToSell": {
                                                "type": "number",
                                                "description": "The number of available units to sell."
                                            },
                                            "orderInProgress": {
                                                "type": "number",
                                                "description": "The number of units you are in the process of shipping."
                                            }
                                        },
                                        "description": "Information about the quantity in inventory"
                                    }
                                }
                            },
                            "example": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<inventory xmlns=\"http:\/\/walmart.com\/\">\n    <sku>1487132332472<\/sku>\n    <availabilityCode>AC<\/availabilityCode>\n    <quantity>\n        <unit>EACH<\/unit>\n        <amount>23<\/amount>\n    <\/quantity>\n<\/inventory>"
                        },
                        "application\/json": {
                            "schema": {
                                "required": [
                                    "availabilityCode",
                                    "quantity",
                                    "sku"
                                ],
                                "type": "object",
                                "properties": {
                                    "sku": {
                                        "type": "string",
                                        "description": "A DSV-provided Product ID. Response will have decoded value."
                                    },
                                    "availabilityCode": {
                                        "type": "string",
                                        "description": "Identifies how to manage the inventory update. AC: The code used for standard inventory updates. Assign this code to an item with normal inventory. AA: An item with infinite inventory. If you set AA as the Availability Code, you don't need to provide inventory for the item.",
                                        "enum": [
                                            "AA",
                                            "AC",
                                            "PO"
                                        ]
                                    },
                                    "quantity": {
                                        "required": [
                                            "unit"
                                        ],
                                        "type": "object",
                                        "properties": {
                                            "unit": {
                                                "type": "string",
                                                "description": "The description of the quantity. Use 'Each' as shown in the provided sample.",
                                                "enum": [
                                                    "EACH"
                                                ]
                                            },
                                            "amount": {
                                                "type": "number",
                                                "description": "The number of the inventory quantity"
                                            },
                                            "availableToSell": {
                                                "type": "number",
                                                "description": "The number of available units to sell."
                                            },
                                            "orderInProgress": {
                                                "type": "number",
                                                "description": "The number of units you are in the process of shipping."
                                            }
                                        },
                                        "description": "Information about the quantity in inventory"
                                    }
                                }
                            },
                            "example": {
                                "sku": "1487132332472",
                                "availabilityCode": "AC",
                                "quantity": {
                                    "unit": "EACH",
                                    "amount": "23"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/xml": {
                                "schema": {
                                    "required": [
                                        "quantity",
                                        "sku"
                                    ],
                                    "type": "object",
                                    "properties": {
                                        "sku": {
                                            "type": "string",
                                            "description": "A DSV-provided Product ID. Response will have decoded value."
                                        },
                                        "quantity": {
                                            "required": [
                                                "amount",
                                                "unit"
                                            ],
                                            "type": "object",
                                            "properties": {
                                                "unit": {
                                                    "type": "string",
                                                    "description": "The unit of measurement. Example: 'EACH'",
                                                    "enum": [
                                                        "EACH"
                                                    ]
                                                },
                                                "amount": {
                                                    "type": "number",
                                                    "description": "The number available in the inventory"
                                                }
                                            },
                                            "description": "Information about the quantity in inventory"
                                        }
                                    },
                                    "xml": {
                                        "name": "Inventory"
                                    }
                                },
                                "example": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<inventory xmlns:ns2=\"http:\/\/walmart.com\/\">\n    <sku>1487132332472<\/sku>\n    <quantity>\n        <unit>EACH<\/unit>\n        <amount>23<\/amount>\n    <\/quantity>\n<\/inventory>\n"
                            },
                            "application\/json": {
                                "schema": {
                                    "required": [
                                        "quantity",
                                        "sku"
                                    ],
                                    "type": "object",
                                    "properties": {
                                        "sku": {
                                            "type": "string",
                                            "description": "A DSV-provided Product ID. Response will have decoded value."
                                        },
                                        "quantity": {
                                            "required": [
                                                "amount",
                                                "unit"
                                            ],
                                            "type": "object",
                                            "properties": {
                                                "unit": {
                                                    "type": "string",
                                                    "description": "The unit of measurement. Example: 'EACH'",
                                                    "enum": [
                                                        "EACH"
                                                    ]
                                                },
                                                "amount": {
                                                    "type": "number",
                                                    "description": "The number available in the inventory"
                                                }
                                            },
                                            "description": "Information about the quantity in inventory"
                                        }
                                    },
                                    "xml": {
                                        "name": "Inventory"
                                    }
                                },
                                "example": {
                                    "sku": "1487132332472",
                                    "quantity": {
                                        "unit": "EACH",
                                        "amount": 23
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "\/v3\/feeds": {
            "post": {
                "tags": [
                    "Inventory"
                ],
                "summary": "Bulk Update",
                "description": "Updates inventory for items in bulk. \nSeller Can either use feed type \"inventory\" or \"DSV_INVENTORY\" \n* Inventory spec 1.4 feed type: inventory \n* Inventory spec 1.5 feed type: DSV_INVENTORY \n\nPlease Note: Multi Node Inventory Update Feed (feedType=DSV_INVENTORY) only supports JSON Request and Responses. Refer to \"DSV_MultiNode_Bulk_Inventory_Update_Request.json\" for the corresponding request sample \n \nRefer to the <a href=\"https:\/\/developer.walmart.com\/doc\/us\/us-dsv\/us-dsv-inventory\/\">guide section<\/a> for more detailed guide around each of the feed types \n\n Refer to the throttling limits before uploading the Feed Files.",
                "operationId": "updateBulkInventory",
                "parameters": [
                    {
                        "name": "feedType",
                        "in": "query",
                        "description": "The feed Type",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "enum": [
                                "inventory",
                                "DSV_INVENTORY"
                            ]
                        }
                    },
                    {
                        "name": "shipNode",
                        "in": "query",
                        "description": "The Distribution Facility \u201cDistributor ID\u201d which uniquely identifies each facility and is autogenerated during DSV account creation. Every time you add\/update a facility in the Supplier Center, a new ID is generated.  Not required in case of Multi Node Inventory Update Feed (feedType=MP_INVENTORY)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_CONSUMER.CHANNEL.TYPE",
                        "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "header",
                        "name": "WM_QOS.CORRELATION_ID",
                        "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "b3261d2d-028a-4ef7-8602-633c23200af6",
                        "x-jane-skip-validation": true
                    },
                    {
                        "in": "header",
                        "name": "WM_SVC.NAME",
                        "description": "Walmart Service Name",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Walmart Service Name",
                        "x-jane-skip-validation": true
                    },
                    {
                        "name": "WM_SEC.TIMESTAMP",
                        "in": "header",
                        "description": "The Epoch timestamp",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "1443748249449"
                    },
                    {
                        "name": "WM_SEC.AUTH_SIGNATURE",
                        "in": "header",
                        "description": "The vendor's digital signature, generated by running the JAR file or custom generation code",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "9fg3TPeRt0WSGbXNGGj4kSQ9L6PMBX.....9Zj5aDyg="
                    },
                    {
                        "name": "WM_CONSUMER.ID",
                        "in": "header",
                        "description": "A unique ID required to access the API",
                        "required": true,
                        "schema": {
                            "type": "string"
                        },
                        "example": "Get the Consumer ID from Developer Center after logging in"
                    }
                ],
                "requestBody": {
                    "description": "Feed file to upload",
                    "content": {
                        "multipart\/form-data": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "format": "binary"
                                    }
                                }
                            },
                            "examples": {
                                "json1": {
                                    "value": {
                                        "InventoryHeader": {
                                            "version": "1.4"
                                        },
                                        "Inventory": [
                                            {
                                                "sku": "CNE498398",
                                                "availabilityCode": "AC",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "amount": "10"
                                                }
                                            },
                                            {
                                                "sku": "ard65005",
                                                "availabilityCode": "AC",
                                                "quantity": {
                                                    "unit": "EACH",
                                                    "availableToSell": "5",
                                                    "orderInProgress": "3"
                                                }
                                            }
                                        ]
                                    }
                                },
                                "DSV_MultiNode_Bulk_Inventory_Update_Request": {
                                    "value": {
                                        "inventoryHeader": {
                                            "version": "1.5"
                                        },
                                        "inventory": [
                                            {
                                                "sku": "190086893939",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 100
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "685387364107_SS4_01",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 21
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "5700521553133_toolsnonwfs_2",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 13
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "1000000352",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 12
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "15088243",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 24
                                                        }
                                                    },
                                                    {
                                                        "shipNode": "1000052",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 12
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                "sku": "AD-01-white-5",
                                                "shipNodes": [
                                                    {
                                                        "shipNode": "10000003527",
                                                        "availabilityCode": "AC",
                                                        "quantity": {
                                                            "unit": "EACH",
                                                            "amount": 20
                                                        }
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                },
                                "xml1": {
                                    "value": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InventoryFeed xmlns=\"http:\/\/walmart.com\/\">\n    <InventoryHeader>\n        <version>1.4<\/version>\n    <\/InventoryHeader>\n    <Inventory>\n        <sku>CNE498398<\/sku>\n        <availabilityCode>AC<\/availabilityCode>\n        <quantity>\n            <unit>EACH<\/unit>\n            <amount>10<\/amount>\n        <\/quantity>\n    <\/Inventory>\n    <Inventory>\n        <sku>ard65005<\/sku>\n        <availabilityCode>AC<\/availabilityCode>\n        <quantity>\n            <unit>EACH<\/unit>\n            <availableToSell>5<\/availableToSell>\n            <orderInProgress>3<\/orderInProgress>\n        <\/quantity>\n    <\/Inventory>\n<\/InventoryFeed>\n"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "content": {
                            "application\/xml": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "feedId": {
                                            "type": "string",
                                            "description": "A unique ID returned from the Bulk Upload API, used for tracking the Feed File. Special characters must be escaped (e.g., feedId: '...3456@789...' must be entered in the URL as '...3456%40789)"
                                        },
                                        "additionalAttributes": {
                                            "type": "object"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "example": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<FeedAcknowledgement xmlns:ns2=\"http:\/\/walmart.com\/\">\n    <feedId>E9C04D1FFD99479FBC1341D56DD5F930@AQMB_wA<\/feedId>\n<\/FeedAcknowledgement>\n"
                            },
                            "application\/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "feedId": {
                                            "type": "string",
                                            "description": "A unique ID returned from the Bulk Upload API, used for tracking the Feed File. Special characters must be escaped (e.g., feedId: '...3456@789...' must be entered in the URL as '...3456%40789)"
                                        },
                                        "additionalAttributes": {
                                            "type": "object"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "example": {
                                    "feedId": "991B8779687C4D5DBC06DF18DB167192@AQkBAQA",
                                    "additionalAttributes": null,
                                    "errors": null
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "InventoryResponse": {
                "required": [
                    "quantity",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "A DSV-provided Product ID. Response will have decoded value."
                    },
                    "quantity": {
                        "required": [
                            "amount",
                            "unit"
                        ],
                        "type": "object",
                        "properties": {
                            "unit": {
                                "type": "string",
                                "description": "The unit of measurement. Example: 'EACH'",
                                "enum": [
                                    "EACH"
                                ]
                            },
                            "amount": {
                                "type": "number",
                                "description": "The number available in the inventory"
                            }
                        },
                        "description": "Information about the quantity in inventory"
                    }
                },
                "xml": {
                    "name": "Inventory"
                }
            },
            "Quantity": {
                "required": [
                    "amount",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The unit of measurement. Example: 'EACH'",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "The number available in the inventory"
                    }
                },
                "description": "Information about the quantity in inventory"
            },
            "Inventory": {
                "required": [
                    "availabilityCode",
                    "quantity",
                    "sku"
                ],
                "type": "object",
                "properties": {
                    "sku": {
                        "type": "string",
                        "description": "A DSV-provided Product ID. Response will have decoded value."
                    },
                    "availabilityCode": {
                        "type": "string",
                        "description": "Identifies how to manage the inventory update. AC: The code used for standard inventory updates. Assign this code to an item with normal inventory. AA: An item with infinite inventory. If you set AA as the Availability Code, you don't need to provide inventory for the item.",
                        "enum": [
                            "AA",
                            "AC",
                            "PO"
                        ]
                    },
                    "quantity": {
                        "required": [
                            "unit"
                        ],
                        "type": "object",
                        "properties": {
                            "unit": {
                                "type": "string",
                                "description": "The description of the quantity. Use 'Each' as shown in the provided sample.",
                                "enum": [
                                    "EACH"
                                ]
                            },
                            "amount": {
                                "type": "number",
                                "description": "The number of the inventory quantity"
                            },
                            "availableToSell": {
                                "type": "number",
                                "description": "The number of available units to sell."
                            },
                            "orderInProgress": {
                                "type": "number",
                                "description": "The number of units you are in the process of shipping."
                            }
                        },
                        "description": "Information about the quantity in inventory"
                    }
                }
            },
            "SupplyQuantity": {
                "required": [
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "type": "string",
                        "description": "The description of the quantity. Use 'Each' as shown in the provided sample.",
                        "enum": [
                            "EACH"
                        ]
                    },
                    "amount": {
                        "type": "number",
                        "description": "The number of the inventory quantity"
                    },
                    "availableToSell": {
                        "type": "number",
                        "description": "The number of available units to sell."
                    },
                    "orderInProgress": {
                        "type": "number",
                        "description": "The number of units you are in the process of shipping."
                    }
                },
                "description": "Information about the quantity in inventory"
            },
            "FeedIdInventory": {
                "type": "object",
                "properties": {
                    "feedId": {
                        "type": "string",
                        "description": "A unique ID returned from the Bulk Upload API, used for tracking the Feed File. Special characters must be escaped (e.g., feedId: '...3456@789...' must be entered in the URL as '...3456%40789)"
                    },
                    "additionalAttributes": {
                        "type": "object"
                    },
                    "errors": {
                        "type": "object"
                    }
                }
            }
        },
        "parameters": {
            "authorization": {
                "name": "Authorization",
                "in": "header",
                "description": "Basic authorization header. Base 64 encodes the Client ID and Client Secret retrieved in step two of the integration steps.",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Basic YzcyOTFjNmItNzI5MC00...."
            },
            "accessToken": {
                "name": "WM_SEC.ACCESS_TOKEN",
                "in": "header",
                "description": "The access token retrieved in the Token API call",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "eyJraWQiOiIzZjVhYTFmNS1hYWE5LTQzM....."
            },
            "channelType": {
                "name": "WM_CONSUMER.CHANNEL.TYPE",
                "in": "header",
                "description": "A unique ID to track the consumer request by channel. Use the Consumer Channel Type received during onboarding",
                "required": true,
                "schema": {
                    "type": "string"
                }
            },
            "correlationId": {
                "name": "WM_QOS.CORRELATION_ID",
                "in": "header",
                "description": "A unique ID which identifies each API call and used to track and debug issues; use a random generated GUID for this ID",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "b3261d2d-028a-4ef7-8602-633c23200af6"
            },
            "svcName": {
                "name": "WM_SVC.NAME",
                "in": "header",
                "description": "Walmart Service Name",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "Walmart Service Name"
            },
            "accept": {
                "name": "Accept",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            },
            "content-type": {
                "name": "Content-Type",
                "in": "header",
                "description": "Only supported Media Type : application\/json",
                "required": true,
                "schema": {
                    "type": "string"
                },
                "example": "application\/json"
            }
        }
    }
}